Install the dependencies

In [6]:
#Install Required Libraries
!pip -q install ultralytics supervision

print("=" * 70)
print("Libraries Installed Successfully")
print("=" * 70)

======================================================================
Libraries Installed Successfully
======================================================================

Import the dependencies

In [7]:
# Import Libraries
import os
import random
import zipfile
import warnings

import numpy as np
import pandas as pd

import torch

from ultralytics import YOLO

warnings.filterwarnings("ignore")

print("=" * 70)
print("Libraries Imported Successfully")
print("=" * 70)

======================================================================
Libraries Imported Successfully
======================================================================

In [8]:
#  Mount Google Drive

from google.colab import drive

drive.mount("/content/drive")

print("=" * 70)
print("Google Drive Mounted Successfully")
print("=" * 70)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
======================================================================
Google Drive Mounted Successfully
======================================================================

In [9]:
# Extract Dataset

ZIP_FILE = "/content/drive/MyDrive/YOLO/data/Suspicious Behavior.v1-v1.802img-2025-02-12-11-30pm.yolov8.zip"

EXTRACT_DIR = "/content/drive/MyDrive/YOLO/data/SuspiciousBehavior"

if not os.path.exists(EXTRACT_DIR):

    with zipfile.ZipFile(ZIP_FILE, "r") as zip_ref:

        zip_ref.extractall(EXTRACT_DIR)

    print("Dataset Extracted Successfully.")

else:

    print("Dataset Already Extracted.")

Dataset Extracted Successfully.

In [10]:
# Random Seed

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

print("=" * 70)
print("Random Seed:", SEED)
print("=" * 70)

======================================================================
Random Seed: 42
======================================================================

In [11]:
# GPU Check

print("=" * 70)

print("PyTorch :", torch.__version__)

print("CUDA Available :", torch.cuda.is_available())

if torch.cuda.is_available():

    DEVICE = 0

    print("GPU :", torch.cuda.get_device_name(0))

else:

    DEVICE = "cpu"

print("=" * 70)

======================================================================
PyTorch : 2.11.0+cu128
CUDA Available : True
GPU : Tesla T4
======================================================================

In [12]:
#  Project Paths

PROJECT_DIR = "/content/drive/MyDrive/YOLO/data/SuspiciousBehavior"

DATA_YAML = os.path.join(PROJECT_DIR, "data.yaml")

RESULT_DIR = os.path.join(PROJECT_DIR, "results")

MODEL_DIR = os.path.join(PROJECT_DIR, "saved_models")

os.makedirs(RESULT_DIR, exist_ok=True)

os.makedirs(MODEL_DIR, exist_ok=True)

print("=" * 70)
print("Project Path Ready")
print("=" * 70)

print(PROJECT_DIR)

======================================================================
Project Path Ready
======================================================================
/content/drive/MyDrive/YOLO/data/SuspiciousBehavior

In [13]:
# Experiment Configuration

IMAGE_SIZE = 640

BATCH_SIZE = 16

EPOCHS = 50

WORKERS = 2

LEARNING_RATE = 0.001

print("=" * 70)

print("Experiment Configuration")

print("=" * 70)

print(f"Image Size : {IMAGE_SIZE}")

print(f"Batch Size : {BATCH_SIZE}")

print(f"Epochs     : {EPOCHS}")

print(f"Workers    : {WORKERS}")

print("=" * 70)

print("Environment Ready")

======================================================================
Experiment Configuration
======================================================================
Image Size : 640
Batch Size : 16
Epochs     : 50
Workers    : 2
======================================================================
Environment Ready

In [14]:
#  Verify Folder Structure

TRAIN_IMAGES = os.path.join(PROJECT_DIR, "train", "images")
TRAIN_LABELS = os.path.join(PROJECT_DIR, "train", "labels")

VALID_IMAGES = os.path.join(PROJECT_DIR, "valid", "images")
VALID_LABELS = os.path.join(PROJECT_DIR, "valid", "labels")

TEST_IMAGES = os.path.join(PROJECT_DIR, "test", "images")
TEST_LABELS = os.path.join(PROJECT_DIR, "test", "labels")

print("=" * 70)
print("YOLO Dataset Structure")
print("=" * 70)

folders = {
    "Train Images": TRAIN_IMAGES,
    "Train Labels": TRAIN_LABELS,
    "Valid Images": VALID_IMAGES,
    "Valid Labels": VALID_LABELS,
    "Test Images": TEST_IMAGES,
    "Test Labels": TEST_LABELS,
    "data.yaml": DATA_YAML
}

all_exist = True

for name, path in folders.items():

    status = os.path.exists(path)

    print(f"{name:<18}: {'✓ Found' if status else '✗ Missing'}")

    if not status:
        all_exist = False

print("=" * 70)

if all_exist:
    print("Dataset Structure Verified Successfully")
else:
    print("Dataset Structure Incomplete")

======================================================================
YOLO Dataset Structure
======================================================================
Train Images      : ✓ Found
Train Labels      : ✓ Found
Valid Images      : ✓ Found
Valid Labels      : ✓ Found
Test Images       : ✓ Found
Test Labels       : ✓ Found
data.yaml         : ✓ Found
======================================================================
Dataset Structure Verified Successfully

In [15]:
#Verify data.yaml

import yaml

with open(DATA_YAML, "r") as f:
    config = yaml.safe_load(f)

print("=" * 70)
print("data.yaml")
print("=" * 70)

for key, value in config.items():
    print(f"{key} : {value}")

======================================================================
data.yaml
======================================================================
train : ../train/images
val : ../valid/images
test : ../test/images
nc : 3
names : ['Fight', 'Normal', 'Poster']
roboflow : {'workspace': 'lazyzone', 'project': 'suspicious-behavior-fxla5', 'version': 1, 'license': 'CC BY 4.0', 'url': 'https://universe.roboflow.com/lazyzone/suspicious-behavior-fxla5/dataset/1'}

In [16]:
#  Verify Image-Label Pairs

def count_files(folder, extensions):

    return len([
        f for f in os.listdir(folder)
        if f.lower().endswith(extensions)
    ])

train_img = count_files(TRAIN_IMAGES, (".jpg", ".jpeg", ".png"))
train_lbl = count_files(TRAIN_LABELS, (".txt",))

valid_img = count_files(VALID_IMAGES, (".jpg", ".jpeg", ".png"))
valid_lbl = count_files(VALID_LABELS, (".txt",))

test_img = count_files(TEST_IMAGES, (".jpg", ".jpeg", ".png"))
test_lbl = count_files(TEST_LABELS, (".txt",))

summary = pd.DataFrame({

    "Split":["Train","Validation","Test"],

    "Images":[train_img, valid_img, test_img],

    "Labels":[train_lbl, valid_lbl, test_lbl]

})

display(summary)

        Split  Images  Labels
0       Train    1688    1688
1  Validation     161     161
2        Test      80      80

In [17]:
#  Verify Classes

print("=" * 70)
print("Class Names")
print("=" * 70)

names = config["names"]

if isinstance(names, dict):
    for idx, cls in names.items():
        print(f"{idx} -> {cls}")
else:
    for idx, cls in enumerate(names):
        print(f"{idx} -> {cls}")

print("=" * 70)

======================================================================
Class Names
======================================================================
0 -> Fight
1 -> Normal
2 -> Poster
======================================================================

In [18]:
# Dataset Summary
TOTAL_IMAGES = train_img + valid_img + test_img

TOTAL_LABELS = train_lbl + valid_lbl + test_lbl

print("=" * 70)
print("DATASET SUMMARY")
print("=" * 70)

print(f"Training Images    : {train_img}")
print(f"Validation Images  : {valid_img}")
print(f"Testing Images     : {test_img}")

print()

print(f"Training Labels    : {train_lbl}")
print(f"Validation Labels  : {valid_lbl}")
print(f"Testing Labels     : {test_lbl}")

print()

print(f"Total Images       : {TOTAL_IMAGES}")
print(f"Total Labels       : {TOTAL_LABELS}")

print("=" * 70)

if TOTAL_IMAGES == TOTAL_LABELS:
    print("Dataset Ready for Training")
else:
    print("Warning: Image/Label count mismatch detected")

======================================================================
DATASET SUMMARY
======================================================================
Training Images    : 1688
Validation Images  : 161
Testing Images     : 80

Training Labels    : 1688
Validation Labels  : 161
Testing Labels     : 80

Total Images       : 1929
Total Labels       : 1929
======================================================================
Dataset Ready for Training

In [19]:
#  Training Configuration

TRAIN_CONFIG = {

    "data": DATA_YAML,

    "imgsz": IMAGE_SIZE,

    "epochs": EPOCHS,

    "batch": BATCH_SIZE,

    "workers": WORKERS,

    "device": DEVICE,

    "seed": SEED,

    "patience": 20,

    "optimizer": "auto",

    "lr0": LEARNING_RATE,

    "pretrained": True,

    "cache": False,

    "verbose": True

}

config_df = pd.DataFrame(

    TRAIN_CONFIG.items(),

    columns=["Parameter","Value"]

)

display(config_df)

     Parameter                                              Value
0         data  /content/drive/MyDrive/YOLO/data/SuspiciousBeh...
1        imgsz                                                640
2       epochs                                                 50
3        batch                                                 16
4      workers                                                  2
5       device                                                  0
6         seed                                                 42
7     patience                                                 20
8    optimizer                                               auto
9          lr0                                              0.001
10  pretrained                                               True
11       cache                                              False
12     verbose                                               True

In [20]:
#Verify Device

print("="*70)

print("Training Device")

print("="*70)

if torch.cuda.is_available():

    print("GPU :", torch.cuda.get_device_name(0))

    print("CUDA :", torch.version.cuda)

    print("Device ID :", DEVICE)

else:

    print("CPU Training")

print("="*70)

======================================================================
Training Device
======================================================================
GPU : Tesla T4
CUDA : 12.8
Device ID : 0
======================================================================

In [21]:
#  Experiment Directories

YOLOV10_DIR = os.path.join(RESULT_DIR,"YOLOv10")

RTDETR_DIR = os.path.join(RESULT_DIR,"RTDETR")

os.makedirs(YOLOV10_DIR,exist_ok=True)

os.makedirs(RTDETR_DIR,exist_ok=True)

print("="*70)

print("Experiment Directories Created")

print("="*70)


print(YOLOV10_DIR)

print(RTDETR_DIR)

======================================================================
Experiment Directories Created
======================================================================
/content/drive/MyDrive/YOLO/data/SuspiciousBehavior/results/YOLOv10
/content/drive/MyDrive/YOLO/data/SuspiciousBehavior/results/RTDETR

In [22]:
# Model Configuration

MODELS = {

    "YOLOv10n":"yolov10n.pt",

    "RT-DETR":"rtdetr-l.pt"

}

model_df = pd.DataFrame(

    MODELS.items(),

    columns=["Model","Pretrained Weight"]

)

display(model_df)

      Model Pretrained Weight
0  YOLOv10n       yolov10n.pt
1   RT-DETR       rtdetr-l.pt

In [23]:
#Training Ready

print("="*70)

print("Training Readiness Check")

print("="*70)

checks = {

    "Dataset YAML": os.path.exists(DATA_YAML),

    "Train Images": os.path.exists(TRAIN_IMAGES),

    "Train Labels": os.path.exists(TRAIN_LABELS),

    "Validation Images": os.path.exists(VALID_IMAGES),

    "Validation Labels": os.path.exists(VALID_LABELS),

    "Test Images": os.path.exists(TEST_IMAGES),

    "Test Labels": os.path.exists(TEST_LABELS)

}

for k,v in checks.items():

    print(f"{k:<22}: {'✓' if v else '✗'}")

print("="*70)

if all(checks.values()):

    print("Dataset is Ready for Training")

else:

    print("Dataset Verification Failed")

======================================================================
Training Readiness Check
======================================================================
Dataset YAML          : ✓
Train Images          : ✓
Train Labels          : ✓
Validation Images     : ✓
Validation Labels     : ✓
Test Images           : ✓
Test Labels           : ✓
======================================================================
Dataset is Ready for Training

In [24]:
# Training Summary

summary = pd.DataFrame({

    "Setting":[

        "Dataset",

        "Models",

        "Epochs",

        "Batch Size",

        "Image Size",

        "Optimizer",

        "Device"

    ],

    "Value":[

        DATA_YAML,

        " YOLOv10n | RT-DETR",

        EPOCHS,

        BATCH_SIZE,

        IMAGE_SIZE,

        "Auto",

        DEVICE

    ]

})

display(summary)

print("="*70)

print("Training Environment Ready")

print("="*70)

      Setting                                              Value
0     Dataset  /content/drive/MyDrive/YOLO/data/SuspiciousBeh...
1      Models                                 YOLOv10n | RT-DETR
2      Epochs                                                 50
3  Batch Size                                                 16
4  Image Size                                                640
5   Optimizer                                               Auto
6      Device                                                  0

======================================================================
Training Environment Ready
======================================================================

YOLOv10n model

In [25]:
from ultralytics import YOLO

YOLO("yolov10n.pt")

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov10n.pt to 'yolov10n.pt': 100% ━━━━━━━━━━━━ 5.6MB 215.9MB/s 0.0s

YOLO(
  (model): DetectionModel(
    (model): Sequential(
      (0): Conv(
        (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): C2f(
        (cv1): Conv(
          (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(48, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (3): Conv(
        (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (4): C2f(
        (cv1): Conv(
          (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0-1): 2 x Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (5): SCDown(
        (cv1): Conv(
          (conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=128, bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): Identity()
        )
      )
      (6): C2f(
        (cv1): Conv(
          (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0-1): 2 x Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (7): SCDown(
        (cv1): Conv(
          (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=256, bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): Identity()
        )
      )
      (8): C2f(
        (cv1): Conv(
          (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (9): SPPF(
        (cv1): Conv(
          (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): MaxPool2d(kernel_size=5, stride=1, padding=2, dilation=1, ceil_mode=False)
      )
      (10): PSA(
        (cv1): Conv(
          (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (attn): Attention(
          (qkv): Conv(
            (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (proj): Conv(
            (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (pe): Conv(
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
        (ffn): Sequential(
          (0): Conv(
            (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (1): Conv(
            (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
      )
      (11): Upsample(scale_factor=2.0, mode='nearest')
      (12): Concat()
      (13): C2f(
        (cv1): Conv(
          (conv): Conv2d(384, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (14): Upsample(scale_factor=2.0, mode='nearest')
      (15): Concat()
      (16): C2f(
        (cv1): Conv(
          (conv): Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(96, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (17): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (18): Concat()
      (19): C2f(
        (cv1): Conv(
          (conv): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): Bottleneck(
            (cv1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (cv2): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
        )
      )
      (20): SCDown(
        (cv1): Conv(
          (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=128, bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): Identity()
        )
      )
      (21): Concat()
      (22): C2fCIB(
        (cv1): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (m): ModuleList(
          (0): CIB(
            (cv1): Sequential(
              (0): Conv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
                (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
                (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
              (2): RepVGGDW(
                (conv): Conv(
                  (conv): Conv2d(256, 256, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3), groups=256, bias=False)
                  (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                  (act): Identity()
                )
                (conv1): Conv(
                  (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
                  (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                  (act): Identity()
                )
                (act): SiLU(inplace=True)
              )
              (3): Conv(
                (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
                (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
              (4): Conv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
                (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
            )
          )
        )
      )
      (23): v10Detect(
        (cv2): ModuleList(
          (0): Sequential(
            (0): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): Sequential(
            (0): Conv(
              (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
          (2): Sequential(
            (0): Conv(
              (conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
          )
        )
        (cv3): ModuleList(
          (0): Sequential(
            (0): Sequential(
              (0): Conv(
                (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=64, bias=False)
                (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(64, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
                (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
            )
            (1): Sequential(
              (0): Conv(
                (conv): Conv2d(80, 80, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=80, bias=False)
                (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(80, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
                (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
            )
            (2): Conv2d(80, 80, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): Sequential(
            (0): Sequential(
              (0): Conv(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
                (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
              (1): Conv(
                (conv): Conv2d(128, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
                (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): SiLU(inplace=True)
              )
            )
            (1): Sequential(

In [26]:
# Load Pretrained YOLOv10n

from ultralytics import YOLO

MODEL_NAME = "yolov10n.pt"

yolov10_model = YOLO(MODEL_NAME)

print("=" * 70)
print("YOLOv10n Loaded Successfully")
print("=" * 70)

print("Model :", MODEL_NAME)

======================================================================
YOLOv10n Loaded Successfully
======================================================================
Model : yolov10n.pt

In [27]:
#  Model Information

print("=" * 70)
print("YOLOv10n Model Summary")
print("=" * 70)

print(yolov10_model.model)

======================================================================
YOLOv10n Model Summary
======================================================================
DetectionModel(
  (model): Sequential(
    (0): Conv(
      (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (1): Conv(
      (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (2): C2f(
      (cv1): Conv(
        (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(48, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): ModuleList(
        (0): Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
      )
    )
    (3): Conv(
      (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (4): C2f(
      (cv1): Conv(
        (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): ModuleList(
        (0-1): 2 x Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
      )
    )
    (5): SCDown(
      (cv1): Conv(
        (conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=128, bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): Identity()
      )
    )
    (6): C2f(
      (cv1): Conv(
        (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): ModuleList(
        (0-1): 2 x Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
      )
    )
    (7): SCDown(
      (cv1): Conv(
        (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=256, bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): Identity()
      )
    )
    (8): C2f(
      (cv1): Conv(
        (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): ModuleList(
        (0): Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
      )
    )
    (9): SPPF(
      (cv1): Conv(
        (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): MaxPool2d(kernel_size=5, stride=1, padding=2, dilation=1, ceil_mode=False)
    )
    (10): PSA(
      (cv1): Conv(
        (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (attn): Attention(
        (qkv): Conv(
          (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): Identity()
        )
        (proj): Conv(
          (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): Identity()
        )
        (pe): Conv(
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): Identity()
        )
      )
      (ffn): Sequential(
        (0): Conv(
          (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (1): Conv(
          (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): Identity()
        )
      )
    )
    (11): Upsample(scale_factor=2.0, mode='nearest')
    (12): Concat()
    (13): C2f(
      (cv1): Conv(
        (conv): Conv2d(384, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): ModuleList(
        (0): Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
      )
    )
    (14): Upsample(scale_factor=2.0, mode='nearest')
    (15): Concat()
    (16): C2f(
      (cv1): Conv(
        (conv): Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(96, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): ModuleList(
        (0): Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
      )
    )
    (17): Conv(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (18): Concat()
    (19): C2f(
      (cv1): Conv(
        (conv): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(192, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): ModuleList(
        (0): Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
      )
    )
    (20): SCDown(
      (cv1): Conv(
        (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=128, bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): Identity()
      )
    )
    (21): Concat()
    (22): C2fCIB(
      (cv1): Conv(
        (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(384, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): ModuleList(
        (0): CIB(
          (cv1): Sequential(
            (0): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (2): RepVGGDW(
              (conv): Conv(
                (conv): Conv2d(256, 256, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3), groups=256, bias=False)
                (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): Identity()
              )
              (conv1): Conv(
                (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, bias=False)
                (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
                (act): Identity()
              )
              (act): SiLU(inplace=True)
            )
            (3): Conv(
              (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (4): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
        )
      )
    )
    (23): v10Detect(
      (cv2): ModuleList(
        (0): Sequential(
          (0): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (1): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): Sequential(
          (0): Conv(
            (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (1): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
        )
        (2): Sequential(
          (0): Conv(
            (conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (1): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (2): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (cv3): ModuleList(
        (0): Sequential(
          (0): Sequential(
            (0): Conv(
              (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=64, bias=False)
              (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(64, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
          (1): Sequential(
            (0): Conv(
              (conv): Conv2d(80, 80, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=80, bias=False)
              (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(80, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
          (2): Conv2d(80, 80, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): Sequential(
          (0): Sequential(
            (0): Conv(
              (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=128, bias=False)
              (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(128, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
          (1): Sequential(
            (0): Conv(
              (conv): Conv2d(80, 80, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=80, bias=False)
              (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(80, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
              (act): SiLU(inplace=True)
            )
          )
          (2): Conv2d(80, 80, kernel_size=(1, 1), stride=(1, 1))
        )
        (2): Sequential(
          (0): Sequential(
            (0): Conv(

In [28]:
#Train YOLOv10n

PROJECT_NAME = "Suspicious_Behavior_Benchmark"
RUN_NAME = "YOLOv10n"

yolov10_results = yolov10_model.train(

    data=DATA_YAML,

    epochs=EPOCHS,

    imgsz=IMAGE_SIZE,

    batch=BATCH_SIZE,

    workers=WORKERS,

    device=DEVICE,

    optimizer="auto",

    project=PROJECT_NAME,

    name=RUN_NAME,

    exist_ok=True,

    seed=SEED,

    patience=20,

    cache=False,

    amp=True,

    val=True,

    plots=True,

    verbose=True
)

Ultralytics 8.4.103 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/YOLO/data/SuspiciousBehavior/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov10n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=YOLOv10n, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=Suspicious_Behavior_Benchmark, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/Suspicious_Behavior_Benchmark/YOLOv10n, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 22.4MB/s 0.0s
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1      9856  ultralytics.nn.modules.block.SCDown          [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1     36096  ultralytics.nn.modules.block.SCDown          [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.PSA             [256, 256]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 20                  -1  1     18048  ultralytics.nn.modules.block.SCDown          [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    282624  ultralytics.nn.modules.block.C2fCIB          [384, 256, 1, True, True]
 23        [16, 19, 22]  1    862498  ultralytics.nn.modules.head.v10Detect        [3, [64, 128, 256]]
YOLOv10n summary: 224 layers, 2,708,210 parameters, 2,708,194 gradients, 8.4 GFLOPs

Transferred 493/595 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 140.1MB/s 0.0s
AMP: checks passed ✅
WARNING ⚠️ train: Slow image access detected (ping: 0.7±0.3 ms, read: 42.9±19.9 MB/s, size: 82.6 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/train/labels... 1688 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1688/1688 63.5it/s 26.6s
train: New cache created: /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Slow image access detected (ping: 1.3±0.6 ms, read: 12.6±8.6 MB/s, size: 67.0 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/valid/labels... 161 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 161/161 52.7it/s 3.1s
val: New cache created: /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/valid/labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 95 weight(decay=0.0), 108 weight(decay=0.0005), 107 bias(decay=0.0)
Plotting labels to /content/runs/detect/Suspicious_Behavior_Benchmark/YOLOv10n/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/Suspicious_Behavior_Benchmark/YOLOv10n
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50       2.9G      1.528      3.426       1.43         87        640: 100% ━━━━━━━━━━━━ 106/106 1.7it/s 1:02
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.7s/it 10.2s
                   all        161        790       0.76      0.173      0.316       0.19

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      3.37G      1.523      2.596      1.435         70        640: 100% ━━━━━━━━━━━━ 106/106 2.8it/s 37.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.3it/s 1.8s
                   all        161        790      0.593      0.643      0.657       0.38

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      3.37G      1.545      2.253      1.452         35        640: 100% ━━━━━━━━━━━━ 106/106 2.4it/s 43.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.2it/s 1.9s
                   all        161        790      0.493      0.706      0.587      0.352

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      3.37G      1.546      1.935      1.434         48        640: 100% ━━━━━━━━━━━━ 106/106 2.7it/s 39.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        161        790      0.672      0.684       0.71      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      3.37G      1.517      1.721      1.406         43        640: 100% ━━━━━━━━━━━━ 106/106 2.7it/s 39.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s
                   all        161        790      0.713      0.722      0.766      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      3.37G      1.522      1.587      1.419         68        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        161        790      0.779      0.682      0.757      0.487

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      3.37G      1.509      1.502      1.408         70        640: 100% ━━━━━━━━━━━━ 106/106 2.8it/s 37.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        161        790      0.688      0.747       0.76      0.414

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      3.37G      1.479      1.436      1.381         58        640: 100% ━━━━━━━━━━━━ 106/106 3.0it/s 35.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.8it/s 3.3s
                   all        161        790      0.818      0.813      0.861      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      3.37G      1.481      1.395      1.388        109        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        161        790      0.839      0.829       0.88      0.556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      3.37G      1.446      1.344      1.368         72        640: 100% ━━━━━━━━━━━━ 106/106 2.8it/s 38.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        161        790      0.825      0.817       0.88      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      3.37G       1.46      1.293      1.364         64        640: 100% ━━━━━━━━━━━━ 106/106 3.0it/s 35.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.1it/s 2.8s
                   all        161        790      0.837       0.84      0.905      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      3.37G      1.446      1.249      1.354         95        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.3it/s 1.8s
                   all        161        790      0.849      0.834      0.894      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      3.37G       1.45      1.237      1.347         31        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.9it/s 3.1s
                   all        161        790      0.827      0.838      0.878      0.574

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      3.37G      1.414      1.197      1.346         44        640: 100% ━━━━━━━━━━━━ 106/106 3.0it/s 35.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 2.0s
                   all        161        790      0.837      0.819      0.894      0.564

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      3.37G      1.403      1.156      1.327         70        640: 100% ━━━━━━━━━━━━ 106/106 2.8it/s 37.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.4it/s 1.8s
                   all        161        790      0.851      0.886      0.923        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      3.37G      1.398      1.154      1.326         80        640: 100% ━━━━━━━━━━━━ 106/106 3.0it/s 35.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        161        790      0.883      0.864      0.914      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      3.37G      1.388      1.144      1.331        106        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.0it/s 2.0s
                   all        161        790      0.907      0.868      0.917      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      3.37G      1.391      1.111      1.323         90        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.2it/s 2.8s
                   all        161        790      0.891      0.896      0.927      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      3.37G      1.367      1.074      1.314         37        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.2it/s 1.9s
                   all        161        790       0.89      0.876      0.925      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      3.37G      1.371      1.078      1.317         84        640: 100% ━━━━━━━━━━━━ 106/106 2.8it/s 37.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        161        790      0.877      0.907      0.925      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      3.37G      1.354      1.044        1.3        124        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.1it/s 2.9s
                   all        161        790      0.883      0.843      0.909        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      3.37G      1.344       1.02      1.301         96        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.2it/s 1.9s
                   all        161        790      0.859      0.897      0.924      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      3.37G      1.315     0.9799      1.278         78        640: 100% ━━━━━━━━━━━━ 106/106 2.8it/s 38.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 2.0s
                   all        161        790      0.871      0.899      0.925      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      3.37G      1.311     0.9901      1.289        129        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.3it/s 2.6s
                   all        161        790      0.906      0.887       0.94      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      3.37G      1.311     0.9829      1.286         74        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 37.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.8it/s 2.2s
                   all        161        790       0.92      0.897      0.928      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      3.37G      1.316     0.9702      1.288         52        640: 100% ━━━━━━━━━━━━ 106/106 2.7it/s 38.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.3it/s 1.8s
                   all        161        790      0.913      0.902      0.934      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      3.37G      1.319     0.9617      1.281         45        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.7it/s 2.2s
                   all        161        790      0.901      0.908      0.936       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      3.37G      1.299     0.9428      1.274         43        640: 100% ━━━━━━━━━━━━ 106/106 2.8it/s 37.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        161        790      0.901       0.92      0.949      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      3.37G      1.293     0.9304      1.266         49        640: 100% ━━━━━━━━━━━━ 106/106 2.7it/s 38.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        161        790      0.895      0.923      0.944      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      3.37G      1.274     0.8863       1.26         68        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.2it/s 1.9s
                   all        161        790      0.915      0.906      0.946      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      3.37G      1.262     0.8876      1.253         26        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 37.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 3.1it/s 1.9s
                   all        161        790      0.911      0.918      0.942      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      3.37G      1.253     0.8703      1.252         94        640: 100% ━━━━━━━━━━━━ 106/106 2.8it/s 37.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 2.6it/s 2.3s
                   all        161        790      0.904      0.914      0.947       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/50      3.37G      1.238     0.8518      1.238        102        640: 100% ━━━━━━━━━━━━ 106/106 2.9it/s 36.2s

In [29]:
# Save Best Model

import os

BEST_YOLOV10 = os.path.join(
    yolov10_results.save_dir,
    "weights",
    "best.pt"
)

LAST_YOLOV10 = os.path.join(
    yolov10_results.save_dir,
    "weights",
    "last.pt"
)

print("=" * 70)
print("YOLOv10n Training Completed")
print("=" * 70)

print("Best Model:")
print(BEST_YOLOV10)

print()

print("Last Model:")
print(LAST_YOLOV10)

print("=" * 70)

======================================================================
YOLOv10n Training Completed
======================================================================
Best Model:
/content/runs/detect/Suspicious_Behavior_Benchmark/YOLOv10n/weights/best.pt

Last Model:
/content/runs/detect/Suspicious_Behavior_Benchmark/YOLOv10n/weights/last.pt
======================================================================

In [30]:
#  Training Summary
summary = pd.DataFrame({

    "Model": ["YOLOv10n"],

    "Dataset": [os.path.basename(DATA_YAML)],

    "Epochs": [EPOCHS],

    "Image Size": [IMAGE_SIZE],

    "Batch Size": [BATCH_SIZE],

    "Optimizer": ["Auto"],

    "Device": [DEVICE]

})

display(summary)

print("=" * 70)
print("YOLOv10n Training Finished Successfully")
print("=" * 70)

      Model    Dataset  Epochs  Image Size  Batch Size Optimizer  Device
0  YOLOv10n  data.yaml      50         640          16      Auto       0

======================================================================
YOLOv10n Training Finished Successfully
======================================================================

In [31]:
# Load Best YOLOv10n

from ultralytics import YOLO

best_yolov10 = YOLO(BEST_YOLOV10)

print("="*70)
print("Best YOLOv10n Loaded Successfully")
print("="*70)

======================================================================
Best YOLOv10n Loaded Successfully
======================================================================

In [32]:
#Evaluate

metrics = best_yolov10.val(

    data=DATA_YAML,

    split="test",

    imgsz=IMAGE_SIZE,

    batch=BATCH_SIZE,

    device=DEVICE,

    verbose=False

)

Ultralytics 8.4.103 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLOv10n summary (fused): 102 layers, 2,265,753 parameters, 0 gradients, 6.5 GFLOPs
WARNING ⚠️ val: Slow image access detected (ping: 0.8±0.4 ms, read: 29.9±10.8 MB/s, size: 68.6 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/test/labels... 80 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 80/80 124.4it/s 0.6s
val: New cache created: /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1s
                   all         80        351      0.919      0.913      0.926      0.636
Speed: 8.1ms preprocess, 6.7ms inference, 0.0ms loss, 1.7ms postprocess per image
Results saved to /content/runs/detect/val

In [33]:
# Extract Metrics

map50 = float(metrics.box.map50)

precision = float(metrics.box.mp)

recall = float(metrics.box.mr)

f1 = float(metrics.box.f1.mean())

print("=" * 70)

print(f"mAP@50    : {map50:.4f}")

print(f"Precision : {precision:.4f}")

print(f"Recall    : {recall:.4f}")

print(f"F1-score  : {f1:.4f}")

print("=" * 70)

======================================================================
mAP@50    : 0.9255
Precision : 0.9189
Recall    : 0.9130
F1-score  : 0.9159
======================================================================

In [34]:
# Save Results
yolov10_results_df = pd.DataFrame({

    "Model": ["YOLOv10n"],

    "mAP@50": [map50],

    "Precision": [precision],

    "Recall": [recall],

    "F1-score": [f1]

})

display(yolov10_results_df)

YOLOV10_RESULT = os.path.join(

    RESULT_DIR,

    "YOLOv10_results.csv"

)

yolov10_results_df.to_csv(

    YOLOV10_RESULT,

    index=False

)

print("=" * 70)

print("YOLOv10 Results Saved Successfully")

print("=" * 70)

print(YOLOV10_RESULT)

      Model    mAP@50  Precision    Recall  F1-score
0  YOLOv10n  0.925516   0.918937  0.912986  0.915886

======================================================================
YOLOv10 Results Saved Successfully
======================================================================
/content/drive/MyDrive/YOLO/data/SuspiciousBehavior/results/YOLOv10_results.csv

RT-DETR model

In [35]:
#  Load Pretrained RT-DETR

from ultralytics import RTDETR

MODEL_NAME = "rtdetr-l.pt"

rtdetr_model = RTDETR(MODEL_NAME)

print("=" * 70)
print("RT-DETR Loaded Successfully")
print("=" * 70)

print("Model :", MODEL_NAME)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/rtdetr-l.pt to 'rtdetr-l.pt': 100% ━━━━━━━━━━━━ 63.4MB 40.4MB/s 1.6s
======================================================================
RT-DETR Loaded Successfully
======================================================================
Model : rtdetr-l.pt

In [36]:
# Model Information

print("=" * 70)
print("RT-DETR Model Summary")
print("=" * 70)

print(rtdetr_model.model)

======================================================================
RT-DETR Model Summary
======================================================================
DetectionModel(
  (model): Sequential(
    (0): HGStem(
      (stem1): Conv(
        (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (stem2a): Conv(
        (conv): Conv2d(32, 16, kernel_size=(2, 2), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (stem2b): Conv(
        (conv): Conv2d(16, 32, kernel_size=(2, 2), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (stem3): Conv(
        (conv): Conv2d(64, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (stem4): Conv(
        (conv): Conv2d(32, 48, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(48, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (pool): MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=True)
    )
    (1): HGBlock(
      (m): ModuleList(
        (0-5): 6 x Conv(
          (conv): Conv2d(48, 48, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(48, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (sc): Conv(
        (conv): Conv2d(336, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (ec): Conv(
        (conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
    )
    (2): DWConv(
      (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=128, bias=False)
      (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): Identity()
    )
    (3): HGBlock(
      (m): ModuleList(
        (0): Conv(
          (conv): Conv2d(128, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(96, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
        (1-5): 5 x Conv(
          (conv): Conv2d(96, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(96, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (sc): Conv(
        (conv): Conv2d(704, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (ec): Conv(
        (conv): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
    )
    (4): DWConv(
      (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=512, bias=False)
      (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): Identity()
    )
    (5): HGBlock(
      (m): ModuleList(
        (0): LightConv(
          (conv1): Conv(
            (conv): Conv2d(512, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): DWConv(
            (conv): Conv2d(192, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=192, bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): ReLU(inplace=True)
          )
        )
        (1-5): 5 x LightConv(
          (conv1): Conv(
            (conv): Conv2d(192, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): DWConv(
            (conv): Conv2d(192, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=192, bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): ReLU(inplace=True)
          )
        )
      )
      (sc): Conv(
        (conv): Conv2d(1664, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (ec): Conv(
        (conv): Conv2d(512, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(1024, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
    )
    (6): HGBlock(
      (m): ModuleList(
        (0): LightConv(
          (conv1): Conv(
            (conv): Conv2d(1024, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): DWConv(
            (conv): Conv2d(192, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=192, bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): ReLU(inplace=True)
          )
        )
        (1-5): 5 x LightConv(
          (conv1): Conv(
            (conv): Conv2d(192, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): DWConv(
            (conv): Conv2d(192, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=192, bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): ReLU(inplace=True)
          )
        )
      )
      (sc): Conv(
        (conv): Conv2d(2176, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (ec): Conv(
        (conv): Conv2d(512, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(1024, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
    )
    (7): HGBlock(
      (m): ModuleList(
        (0): LightConv(
          (conv1): Conv(
            (conv): Conv2d(1024, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): DWConv(
            (conv): Conv2d(192, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=192, bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): ReLU(inplace=True)
          )
        )
        (1-5): 5 x LightConv(
          (conv1): Conv(
            (conv): Conv2d(192, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): DWConv(
            (conv): Conv2d(192, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=192, bias=False)
            (bn): BatchNorm2d(192, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): ReLU(inplace=True)
          )
        )
      )
      (sc): Conv(
        (conv): Conv2d(2176, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (ec): Conv(
        (conv): Conv2d(512, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(1024, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
    )
    (8): DWConv(
      (conv): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=1024, bias=False)
      (bn): BatchNorm2d(1024, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): Identity()
    )
    (9): HGBlock(
      (m): ModuleList(
        (0): LightConv(
          (conv1): Conv(
            (conv): Conv2d(1024, 384, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(384, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): DWConv(
            (conv): Conv2d(384, 384, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=384, bias=False)
            (bn): BatchNorm2d(384, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): ReLU(inplace=True)
          )
        )
        (1-5): 5 x LightConv(
          (conv1): Conv(
            (conv): Conv2d(384, 384, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(384, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): DWConv(
            (conv): Conv2d(384, 384, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=384, bias=False)
            (bn): BatchNorm2d(384, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): ReLU(inplace=True)
          )
        )
      )
      (sc): Conv(
        (conv): Conv2d(3328, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(1024, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
      (ec): Conv(
        (conv): Conv2d(1024, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(2048, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): ReLU(inplace=True)
      )
    )
    (10): Conv(
      (conv): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): Identity()
    )
    (11): AIFI(
      (ma): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
      )
      (fc1): Linear(in_features=256, out_features=1024, bias=True)
      (fc2): Linear(in_features=1024, out_features=256, bias=True)
      (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0, inplace=True)
      (dropout1): Dropout(p=0, inplace=True)
      (dropout2): Dropout(p=0, inplace=True)
      (act): GELU(approximate='none')
    )
    (12): Conv(
      (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (13): Upsample(scale_factor=2.0, mode='nearest')
    (14): Conv(
      (conv): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): Identity()
    )
    (15): Concat()
    (16): RepC3(
      (cv1): Conv(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): Sequential(
        (0): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
        (1): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
        (2): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
      )
      (cv3): Identity()
    )
    (17): Conv(
      (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (18): Upsample(scale_factor=2.0, mode='nearest')
    (19): Conv(
      (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): Identity()
    )
    (20): Concat()
    (21): RepC3(
      (cv1): Conv(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): Sequential(
        (0): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
        (1): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
        (2): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
      )
      (cv3): Identity()
    )
    (22): Conv(
      (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (23): Concat()
    (24): RepC3(
      (cv1): Conv(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (m): Sequential(
        (0): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
        (1): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
        (2): RepConv(
          (act): SiLU(inplace=True)
          (conv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
          (conv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): Identity()
          )
        )
      )
      (cv3): Identity()
    )
    (25): Conv(

In [37]:
# Train RT-DETR

PROJECT_NAME = "Suspicious_Behavior_Benchmark"

RUN_NAME = "RTDETR"

rtdetr_results = rtdetr_model.train(

    data=DATA_YAML,

    epochs=4,

    imgsz=IMAGE_SIZE,

    batch=BATCH_SIZE,

    workers=WORKERS,

    device=DEVICE,

    optimizer="auto",

    project=PROJECT_NAME,

    name=RUN_NAME,

    exist_ok=True,

    seed=SEED,

    patience=2,

    cache=False,

    amp=True,

    val=True,

    plots=True,

    verbose=True

)

Ultralytics 8.4.103 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/YOLO/data/SuspiciousBehavior/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=4, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=RTDETR, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=2, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=Suspicious_Behavior_Benchmark, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=3
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7308017  ultralytics.nn.modules.head.RTDETRDecoder    [3, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,812,241 parameters, 32,812,241 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
WARNING ⚠️ train: Slow image access detected (ping: 0.7±0.2 ms, read: 21.6±13.3 MB/s, size: 70.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/train/labels.cache... 1688 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1688/1688 393.3Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Slow image access detected (ping: 0.7±0.4 ms, read: 25.7±13.2 MB/s, size: 61.2 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/valid/labels.cache... 161 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 161/161 5.6Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR
Starting training for 4 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
        1/4      12.4G     0.7475      1.547     0.4043         87        640: 100% ━━━━━━━━━━━━ 106/106 1.4s/it 2:29
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.5s/it 9.1s
                   all        161        790      0.922      0.938      0.952      0.588

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
        2/4      12.7G     0.4887     0.5147     0.2399         70        640: 100% ━━━━━━━━━━━━ 106/106 1.3s/it 2:15
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.5it/s 4.0s
                   all        161        790      0.932      0.931      0.952       0.64

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
        3/4      12.4G     0.4601     0.4932     0.2283         35        640: 100% ━━━━━━━━━━━━ 106/106 1.4s/it 2:25
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.5it/s 4.0s
                   all        161        790      0.933      0.933      0.958      0.642

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
        4/4      12.5G     0.4321     0.4787     0.2076         48        640: 100% ━━━━━━━━━━━━ 106/106 1.4s/it 2:25
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.5it/s 3.9s
                   all        161        790      0.937      0.955      0.961      0.677

4 epochs completed in 0.176 hours.
Optimizer stripped from /content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR/weights/last.pt, 66.2MB
Optimizer stripped from /content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR/weights/best.pt, 66.2MB

Validating /content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR/weights/best.pt...
Ultralytics 8.4.103 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,989,905 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.1s/it 6.5s
                   all        161        790      0.936      0.956      0.962      0.676
                 Fight         88         91      0.931      0.956      0.963      0.737
                Normal         88        503       0.89      0.916      0.934      0.544
                Poster         42        196      0.987      0.995      0.988      0.749
Speed: 0.3ms preprocess, 25.3ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to /content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR

In [38]:
#Save Best Model
import os

BEST_RTDETR = os.path.join(

    rtdetr_results.save_dir,

    "weights",

    "best.pt"

)

LAST_RTDETR = os.path.join(

    rtdetr_results.save_dir,

    "weights",

    "last.pt"

)

print("=" * 70)
print("RT-DETR Training Completed")
print("=" * 70)

print("Best Model:")
print(BEST_RTDETR)

print()

print("Last Model:")
print(LAST_RTDETR)

print("=" * 70)

======================================================================
RT-DETR Training Completed
======================================================================
Best Model:
/content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR/weights/best.pt

Last Model:
/content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR/weights/last.pt
======================================================================

In [39]:
#  Training Summary

summary = pd.DataFrame({

    "Model": ["RT-DETR"],

    "Dataset": [os.path.basename(DATA_YAML)],

    "Epochs": [EPOCHS],

    "Image Size": [IMAGE_SIZE],

    "Batch Size": [BATCH_SIZE],

    "Optimizer": ["Auto"],

    "Device": [DEVICE]

})

display(summary)

print("=" * 70)
print("RT-DETR Training Finished Successfully")
print("=" * 70)

     Model    Dataset  Epochs  Image Size  Batch Size Optimizer  Device
0  RT-DETR  data.yaml      50         640          16      Auto       0

======================================================================
RT-DETR Training Finished Successfully
======================================================================

In [40]:
# Load Best RT-DETR Model

from ultralytics import RTDETR

best_rtdetr = RTDETR(BEST_RTDETR)

print("=" * 70)
print("Best RT-DETR Model Loaded Successfully")
print("=" * 70)

print(BEST_RTDETR)

======================================================================
Best RT-DETR Model Loaded Successfully
======================================================================
/content/runs/detect/Suspicious_Behavior_Benchmark/RTDETR/weights/best.pt

In [41]:
# Evaluate RT-DETR

metrics = best_rtdetr.val(

    data=DATA_YAML,

    split="test",

    imgsz=IMAGE_SIZE,

    batch=BATCH_SIZE,

    device=DEVICE,

    verbose=False

)

Ultralytics 8.4.103 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,989,905 parameters, 0 gradients, 103.4 GFLOPs
WARNING ⚠️ val: Slow image access detected (ping: 0.6±0.3 ms, read: 41.1±18.2 MB/s, size: 68.2 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /content/drive/MyDrive/YOLO/data/SuspiciousBehavior/test/labels.cache... 80 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 80/80 30.5Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.1s/it 5.5s
                   all         80        351      0.909      0.962      0.946      0.643
Speed: 8.9ms preprocess, 46.8ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /content/runs/detect/val-2

In [42]:
# Extract Evaluation Metrics

map50 = float(metrics.box.map50)

precision = float(metrics.box.mp)

recall = float(metrics.box.mr)

f1 = float(metrics.box.f1.mean())

rtdetr_results_df = pd.DataFrame({

    "Model": ["RT-DETR"],

    "mAP@50": [map50],

    "Precision": [precision],

    "Recall": [recall],

    "F1-score": [f1]

})

display(rtdetr_results_df)

     Model    mAP@50  Precision   Recall  F1-score
0  RT-DETR  0.945503   0.909349  0.96152  0.934026

In [43]:
# Save Results

RTDETR_RESULT = os.path.join(

    RESULT_DIR,

    "RTDETR_results.csv"

)

rtdetr_results_df.to_csv(

    RTDETR_RESULT,

    index=False

)

print("=" * 70)

print("RT-DETR Results Saved Successfully")

print("=" * 70)

print(RTDETR_RESULT)

======================================================================
RT-DETR Results Saved Successfully
======================================================================
/content/drive/MyDrive/YOLO/data/SuspiciousBehavior/results/RTDETR_results.csv

In [44]:
# Evaluation Summary

summary = rtdetr_results_df.copy()

display(summary)

print("=" * 70)

print("RT-DETR Evaluation Completed")

print("=" * 70)

     Model    mAP@50  Precision   Recall  F1-score
0  RT-DETR  0.945503   0.909349  0.96152  0.934026

======================================================================
RT-DETR Evaluation Completed
======================================================================

In [45]:
#  Load Evaluation Results

import os
import pandas as pd

YOLOV10_RESULT = os.path.join(
    RESULT_DIR,
    "YOLOv10_results.csv"
)

RTDETR_RESULT = os.path.join(
    RESULT_DIR,
    "RTDETR_results.csv"
)

yolov10_df = pd.read_csv(YOLOV10_RESULT)
rtdetr_df = pd.read_csv(RTDETR_RESULT)

print("=" * 70)
print("Evaluation Results Loaded Successfully")
print("=" * 70)

======================================================================
Evaluation Results Loaded Successfully
======================================================================

In [46]:
#Comparison Table

comparison = pd.concat(

    [

        yolov10_df,

        rtdetr_df

    ],

    ignore_index=True

)

comparison = comparison.round(4)

display(comparison)

      Model  mAP@50  Precision  Recall  F1-score
0  YOLOv10n  0.9255     0.9189  0.9130    0.9159
1   RT-DETR  0.9455     0.9093  0.9615    0.9340

In [47]:
# Model Ranking
comparison = comparison.sort_values(

    by="F1-score",

    ascending=False

).reset_index(drop=True)

comparison.insert(

    0,

    "Rank",

    range(1, len(comparison)+1)

)

display(comparison)

   Rank     Model  mAP@50  Precision  Recall  F1-score
0     1   RT-DETR  0.9455     0.9093  0.9615    0.9340
1     2  YOLOv10n  0.9255     0.9189  0.9130    0.9159

In [48]:
# Best Model

best_model = comparison.iloc[0]

print("=" * 70)

print("BEST DETECTION MODEL")

print("=" * 70)

print(f"Model      : {best_model['Model']}")
print(f"Precision  : {best_model['Precision']:.4f}")
print(f"Recall     : {best_model['Recall']:.4f}")
print(f"F1-score   : {best_model['F1-score']:.4f}")

print("=" * 70)

======================================================================
BEST DETECTION MODEL
======================================================================
Model      : RT-DETR
Precision  : 0.9093
Recall     : 0.9615
F1-score   : 0.9340
======================================================================

In [49]:
#  Save Final Comparison

FINAL_RESULT = os.path.join(

    RESULT_DIR,

    "Final_Model_Comparison.csv"

)

comparison.to_csv(

    FINAL_RESULT,

    index=False

)

print("=" * 70)

print("Final Comparison Saved Successfully")

print("=" * 70)

print(FINAL_RESULT)

======================================================================
Final Comparison Saved Successfully
======================================================================
/content/drive/MyDrive/YOLO/data/SuspiciousBehavior/results/Final_Model_Comparison.csv

In [50]:
# Benchmark Summary

display(comparison)

print("=" * 70)

print("Benchmark Completed Successfully")

print("=" * 70)

   Rank     Model  mAP@50  Precision  Recall  F1-score
0     1   RT-DETR  0.9455     0.9093  0.9615    0.9340
1     2  YOLOv10n  0.9255     0.9189  0.9130    0.9159

======================================================================
Benchmark Completed Successfully
======================================================================